### ISSUE TITLE
ROBLOX Game Client GUI not appearing on a secondary account.

### ISSUE THREAD

**Issue by scripterStarter** [frickinfire/vanilla-issue-tracker#1]
This problem has been happening since I download Vanilla. 
Whenever I open up the launcher and press Edit, Play, or Host nothing shows up. 

Meanwhile on Task Manager, it shows that the clients are under Vanilla Launcher.
![image](https://github.com/frickinfire/vanilla-issue-tracker/assets/68967701/754097a1-f97e-4373-b2dc-dc9eab9d1963)

I think this is happening because the clients are showing on my admin account (Pi). While my main account (pi2) isn't seeing the clients.

**Comment by frickinfire** [comment]
this is because Vanilla has to run as admin to  get the web service working. my recommendation  is to sign out of your admin account or make your user account an administrator.

**Comment by frickinfire** [comment]
this may be fixed in a future update by having the hosts modifier be a separate executable, but for now thats how it is

**Comment by scripterStarter** [comment]
Now my clients are gone?
![image](https://github.com/frickinfire/vanilla-issue-tracker/assets/68967701/87a8d35e-f14d-4e1b-a48f-a31041279e3c)
