### ISSUE TITLE
The avatar doesn't show upon re-opening but appears in the game since it's saved

### ISSUE THREAD

**Issue by sorelight** [frickinfire/vanilla-issue-tracker#5]
When doing changes to your avatar, It does save but It won't show when re-opening the Vanilla. You can still see your avatar If you join a game.

![image](https://github.com/frickinfire/vanilla-issue-tracker/assets/97408934/49ba7dbb-338d-41f1-b218-65a1fcb37aa9)

**Comment by frickinfire** [comment]
was fixed
