### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by sorelight** [frickinfire/vanilla-issue-tracker#6]
This may be a common error, but see the difference:
![image](https://github.com/frickinfire/vanilla-issue-tracker/assets/97408934/629c1d34-34d7-49be-83ef-019873515316)
![image](https://github.com/frickinfire/vanilla-issue-tracker/assets/97408934/9e53afff-2aba-49cd-939a-0e25741f0572)
Notice anything?

**Comment by frickinfire** [comment]
was fixed
